### ISSUE TITLE
is there a plan that upgrade spectre.css to latest version?

### ISSUE THREAD

**Issue by glfeng318** [mynomoto/hoplon-spectre.css#1]
hi there,

is there a plan that upgrade spectre.css to latest version?

**Comment by mynomoto** [comment]
@feng5 Not really at this moment. I recently found and have being studying [tachyons](tachyons.io) and I think that is a better abstraction over css. I would be glad to accept an pr with the update or transfering the ownership of this project. I will keep this issue open to remind me to add a notice on the readme with this info.
